security:
    encoders:
        Estina\Bundle\HomeBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        nta_users:
            entity: { class: Estina\Bundle\HomeBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        nta_login:
            provider: nta_users
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: user_profile
                csrf_parameter: _token


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
